# Generated by Django 2.1.3 on 2018-11-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milonga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('duracao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ParDanca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Pares',
                'verbose_name': 'Par',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('milonga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='milonga.Milonga')),
            ],
        ),
        migrations.AddField(
            model_name='pardanca',
            name='cavalheiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cavalheiro', to='milonga.Pessoa'),
        ),
        migrations.AddField(
            model_name='pardanca',
            name='dama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dama', to='milonga.Pessoa'),
        ),
        migrations.AddField(
            model_name='pardanca',
            name='tanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='milonga.Tanda'),
        ),
    ]
