# Generated by Django 2.1.3 on 2018-11-16 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('milonga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milonga',
            name='duracao',
        ),
        migrations.AddField(
            model_name='milonga',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2018, 11, 16, 12, 39, 47, 273641, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milonga',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2018, 11, 16, 12, 40, 18, 233553, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
