# Generated by Django 2.1.3 on 2018-11-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milonga', '0003_mudanca_nomenclatura_tanda_para_danca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pardanca',
            name='cavalheiro',
        ),
        migrations.RemoveField(
            model_name='pardanca',
            name='dama',
        ),
        migrations.RemoveField(
            model_name='pardanca',
            name='danca',
        ),
        migrations.AddField(
            model_name='danca',
            name='cavalheiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cavalheiro', to='milonga.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danca',
            name='dama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dama', to='milonga.Pessoa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParDanca',
        ),
    ]
